rpcserver:
  proto: tcp
  port: 8000

httpserver:
  port: 8080

logger:
  # debug,info,warn,error,fatal,panic
  level: debug

plasma:
    datadir: testdata
    networkId: 1

rootchain:
    type: 0
    url: http://localhost:8545
    cxAddr: "248c20ffa55f91a8a6231e5484d7e2e9bcf47c8d" 
    cxFileName: "rootchain/deploy/contract_data/RootChain.json" 
