rpcserver:
  proto: tcp
  port: 8000

httpserver:
  port: 8080

p2pserver:
  port: 4001

logger:
  # debug,info,warn,error,fatal,panic
  level: debug

plasma:
    datadir: testdata
    networkId: 1
    bootstrapNodes:

rootchain:
    operPwd: wzp
    url: http://119.28.248.204:8546
    cxAddr: "f9f927ec90320c257b0ba5a597c50c175a155c14" 
    cxFileName: "rootchain/deploy/contract_data/RootChain.json" 
    fromBlock: 2000
