rpcserver:
  proto: tcp
  port: 8000

httpserver:
  port: 8080

p2pserver:
  port: 4001

logger:
  # debug,info,warn,error,fatal,panic
  level: debug

plasma:
    datadir: testdata
    networkId: 1
    bootstrapNodes:
    privKey: CAASqAkwggSkAgEAAoIBAQCdXVIKZEiZF9ClGQr6FX/LciJ6AsU/V/tkNj3vli3LoORrydZScdmbBM+IcJQYQCs1plu7+MS6oEURwi4xW3CqVvaF/L15b5KiMIHfP8siS0u3+2pgaVvV/mP/+pZx/5De3To7oGe2Yn30BpMYqV65EdZehoqHnuwGtTsnNoOikt8g9Agd6gBXbVIQP9G0YLpMSF6I33NH7/faQZfYxvRHsqnaUBp39Ns3KLtv3V3rF51+RNXj7ZeBJQMRM+lH+PMBvCwXCRclVFWY33YA5orabR8GUf95Fd1JOO+z93xkwmep4ARssqVi3fzMKu0ErbfpiuOZ99m6SBXnglY0HKB9AgMBAAECggEBAI0zzYfRkGr+uZNLM1RPskolcdY1YjSCh+rV2SGAijsrdYtaott7mRzGZkoxalGQUrVjPvEeObiUUyWqLbTQLfpK6g40SPgMK3EpQX/HSEjPc3P1PvCf2W3dRHHOsuw7vAyeScBzIFzBZ+9tbtQ0NfCulsJeyzMCYRtrx1ZaTiezZgdfNTXuQZfXeB9BHdsufARO3xRnCtFPxpz85q0eohbQ/PG9OYoSuRFXMOQjxbQ9wf1mNKvwdPvdFBJeHuK5wAHgJtgQtS1hUvTWQl/YHjCjfYV8PAEc5neo2CWQGwydU+S5cR6EDcsQcy6ecBi15ne+blZBmZM6SQQhNFXlSAECgYEAzQZVwR3GBUzAAp9d/XSjGDYEjbh5OmFEHxsJzlBdLuWpyyVtj0KcnmbWMSgvl8iHSJHTBKLqtKAMCw267ZcOoDVxKI0QJjdMdeqV4tux/YI9hN9jNeZQvdF1qlseNa7yNGn09yVnKt2psclr+221f5CZxBqMSRe2Sy+dofyTNQECgYEAxH1zPPT2rqrCsaF6GkQgnPtA0IenubI4XNuENxZ9iddIG2Ns4Jaa2v6xT3hI6t46Y0+B47PdHymP7502egvTqmoDJX5lBPaaxRuKicJZNOz7qG0438B5xyMRadWqVhd0wuZJY3TgoUKCvQTYh36v2r6PtGCkg/sSmJ5ogJuwv30CgYEAvblNBcXtht39GPAs4+xZOIBUOmkpFZMInNhCfL71W/5+31QlTFrR3+s97oNHd2fDeK4o3bN9CeTJADmWb2JH0I1jx6ix9wtZIA0S4rl2vicVkq29exVERkNcZWaoT/kyfLpIS6Q7EfnJnJHN8P8W45MGF+iRRNpCgNTxRAMcngECgYBkMHd3KI00KPwXaPgCtqROh0rYSaN7a2WT65ayJDSk+XHaDUtyBTk221F77SB5KhFpnBvmCEuC3UV4b5hciPVH2sB5+MX3zurCALYWYlPsSb5UdkTeyp0NrlLtvTYaqeEulA/tt6XmdCyHxxXFmRKAHlTWK8UXSwmDappsoXZxXQKBgF/2Kr2Rfy3BkKposu7oqVkjLkUXhdsc96DLawgJrj04w93muXbYj6A8te6K1oiW3G5K/C2w5/RKe1jRXZBPt0WO6ob/qQfqoRrd9Vq3mYOKyO/tolZPqY9OrECgc1p3Zk6FLUhHHesUkCLqlBGo0fR2z67EeaDzKwU2AcXeeR0j

rootchain:
    operPwd: wzp
    url: http://119.28.248.204:8546
    cxAddr: "f9f927ec90320c257b0ba5a597c50c175a155c14" 
    cxFileName: "rootchain/deploy/contract_data/RootChain.json" 
    fromBlock: 2000
